// =====================================================================
//  PRODUCT-WIDE CONSTANTS
// =====================================================================

/**
 * The non-negotiable disclaimer. It appears prominently at the top of
 * every generated report. Edit the wording with your engineer if needed,
 * but it must always clearly state the output is a draft aid, not an
 * engineered or approved document.
 */
export const DISCLAIMER =
  "DRAFT — PRELIMINARY ANALYSIS AND DRAFTING AID ONLY. " +
  "This document was generated by software to help organize a permit submittal. " +
  "It is NOT an engineered document, NOT a code-compliance determination, and NOT approved by any authority. " +
  "Every input, assumption, code value, and result herein MUST be independently reviewed, verified, " +
  "corrected as needed, and stamped by a California-licensed professional engineer before any use, " +
  "submittal, or reliance. Values marked PLACEHOLDER are not real answers and must be supplied by the engineer.";

/** The code basis these data files are labeled against (subject to verification). */
export const CODE_BASIS = [
  "2025 California Fire Code (CFC) — high-piled combustible storage (Chapter 32)",
  "2025 California Building Code (CBC)",
  "ASCE 7-22 — seismic design (as referenced by the 2025 CBC)",
  "ACI 318 — anchoring to concrete (Chapter 17)",
  "ANSI/RMI MH16.1 — design of steel storage racks",
  "Local jurisdiction (city / county) submittal requirements",
];

export const APP_TITLE = "Storage-Rack Permit Package — Draft Preparation Aid";
